# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rawingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rawingredients.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('post_drink_instruction', models.TextField(blank=True, max_length=500, null=True)),
                ('number_of_ratings_global', models.IntegerField(default=0)),
                ('average_rating_global', models.IntegerField(default=0)),
                ('number_of_ratings_local', models.IntegerField(default=0)),
                ('average_rating_local', models.IntegerField(default=0)),
                ('number_of_times_consumed_local', models.IntegerField(default=0)),
                ('number_of_times_consumed_global', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, default='No Comments', max_length=256, null=True)),
                ('ingredients', models.ManyToManyField(through='recepies.IngredientList', to='rawingredients.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='quantity_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.MeasurementSize'),
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='recepie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.Recepie'),
        ),
    ]
